/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Me: () => import('#app/auth/controllers/me_controller'),
    SignIn: () => import('#app/auth/controllers/sign_in_controller'),
    SignOut: () => import('#app/auth/controllers/sign_out_controller'),
    SignUp: () => import('#app/auth/controllers/sign_up_controller'),
  },
}
