/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    ForgotPassword: () => import('#app/auth/controllers/forgot_password_controller'),
    Me: () => import('#app/auth/controllers/me_controller'),
    ResetPassword: () => import('#app/auth/controllers/reset_password_controller'),
    SignIn: () => import('#app/auth/controllers/sign_in_controller'),
    SignOut: () => import('#app/auth/controllers/sign_out_controller'),
    SignUp: () => import('#app/auth/controllers/sign_up_controller'),
    VerifyResetCode: () => import('#app/auth/controllers/verify_reset_code_controller'),
  },
  focus: {
    AbandonActiveSession: () => import('#app/focus/controllers/abandon_active_session_controller'),
    ActiveSession: () => import('#app/focus/controllers/active_session_controller'),
    CompleteSession: () => import('#app/focus/controllers/complete_session_controller'),
    ListSessions: () => import('#app/focus/controllers/list_sessions_controller'),
    PauseSession: () => import('#app/focus/controllers/pause_session_controller'),
    ResumeSession: () => import('#app/focus/controllers/resume_session_controller'),
    StartSession: () => import('#app/focus/controllers/start_session_controller'),
  },
}
