/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AuthUserTransformer from '#app/auth/transformers/user_transformer'

export namespace Data {
  export namespace Auth {
    export type User = InferData<AuthUserTransformer>
    export namespace User {
      export type Variants = InferVariants<AuthUserTransformer>
    }
  }
}
